<?php

/**
 * Zym Framework
 *
 * This file is part of the Zym package.
 *
 * @link      https://github.com/geoffreytran/zym for the canonical source repository
 * @copyright Copyright (c) 2014 Geoffrey Tran <geoffrey.tran@gmail.com>
 * @license   http://opensource.org/licenses/BSD-3-Clause BSD-3 License
 */

namespace Zym\Bundle\RouterBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;

class RouterResourcePass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        if (!$container->getParameter('router.resource')) {
            return;
        }

        $yaml = <<<EOF
# generated by ZymRouterBundle
# do not edit this file
_ZymRouterBundle: { resource: ., type: orm }
_app: { resource: "{$container->getParameter('router.resource')}" }

EOF;

        $file = $container->getParameter('kernel.cache_dir').'/zym_router/routing.yml';

        if (!is_dir($dir = dirname($file))) {
            mkdir($dir, 0777, true);
        }
        file_put_contents($file, $yaml);

        $container->setParameter('router.resource', $file);
    }
}