<?php

namespace Zym\Bundle\RouterBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;

class RouterResourcePass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        if (!$container->getParameter('router.resource')) {
            return;
        }

        $yaml = <<<EOF
# generated by ZymRouterBundle
# do not edit this file
_ZymRouterBundle: { resource: ., type: orm }
_app: { resource: "{$container->getParameter('router.resource')}" }

EOF;

        $file = $container->getParameter('kernel.cache_dir').'/zym_router/routing.yml';

        if (!is_dir($dir = dirname($file))) {
            mkdir($dir, 0777, true);
        }
        file_put_contents($file, $yaml);

        $container->setParameter('router.resource', $file);
    }
}